<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <RuntimeFrameworkVersion>10.0.10</RuntimeFrameworkVersion>
    <TargetLatestRuntimePatch>false</TargetLatestRuntimePatch>
    <RollForward>Disable</RollForward>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>Comote.InputBroker</AssemblyName>
    <RootNamespace>Comote.InputBroker</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyVersion>1.6.0.10</AssemblyVersion>
    <FileVersion>1.6.0.10</FileVersion>
    <Version>1.6.0-preview.10</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InputCore\Comote.InputCore.csproj" />
  </ItemGroup>
</Project>
