#pragma once

#ifdef _KERNEL_MODE
#include <ntddk.h>
#include <devioctl.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#define COMOTE_PROTOCOL_MAGIC 0x32485643UL
#define COMOTE_PROTOCOL_VERSION 2UL

#define COMOTE_DRIVER_VERSION_MAJOR 0UL
#define COMOTE_DRIVER_VERSION_MINOR 2UL
#define COMOTE_DRIVER_VERSION_PATCH 0UL
#define COMOTE_DRIVER_VERSION_BUILD 0UL

#define COMOTE_CAPABILITY_KEYBOARD_6KRO 0x00000001UL
#define COMOTE_CAPABILITY_MOUSE_RELATIVE 0x00000002UL
#define COMOTE_CAPABILITY_MOUSE_FIVE_BUTTONS 0x00000004UL
#define COMOTE_CAPABILITY_MOUSE_VERTICAL_WHEEL 0x00000008UL
#define COMOTE_CAPABILITY_MOUSE_HORIZONTAL_WHEEL 0x00000010UL
#define COMOTE_CAPABILITY_RELEASE_ALL 0x00000020UL
#define COMOTE_CAPABILITY_STRICT_SEQUENCE 0x00000040UL
#define COMOTE_CAPABILITY_SYSTEM_ONLY 0x00000080UL
#define COMOTE_CAPABILITY_RELEASE_ON_CLOSE 0x00000100UL
#define COMOTE_CAPABILITY_RELEASE_ON_POWER_DOWN 0x00000200UL
#define COMOTE_CAPABILITY_MOUSE_ABSOLUTE 0x00000400UL

#define COMOTE_KEYBOARD_MAX_KEYS 6U
#define COMOTE_MOUSE_BUTTON_MASK 0x1FU
#define COMOTE_MOUSE_MAX_DELTA 32767L
#define COMOTE_MOUSE_MAX_WHEEL_DELTA 127L
#define COMOTE_MOUSE_MAX_ABSOLUTE_COORDINATE 32767L

#define FILE_DEVICE_COMOTE_VIRTUAL_HID 0x8000U

#define IOCTL_COMOTE_GET_VERSION \
    CTL_CODE( \
        FILE_DEVICE_COMOTE_VIRTUAL_HID, \
        0x800U, \
        METHOD_BUFFERED, \
        FILE_READ_DATA)

#define IOCTL_COMOTE_GET_CAPABILITIES \
    CTL_CODE( \
        FILE_DEVICE_COMOTE_VIRTUAL_HID, \
        0x801U, \
        METHOD_BUFFERED, \
        FILE_READ_DATA)

#define IOCTL_COMOTE_RELEASE_ALL \
    CTL_CODE( \
        FILE_DEVICE_COMOTE_VIRTUAL_HID, \
        0x802U, \
        METHOD_BUFFERED, \
        FILE_WRITE_DATA)

#define IOCTL_COMOTE_SET_KEYBOARD_STATE \
    CTL_CODE( \
        FILE_DEVICE_COMOTE_VIRTUAL_HID, \
        0x803U, \
        METHOD_BUFFERED, \
        FILE_WRITE_DATA)

#define IOCTL_COMOTE_MOUSE_RELATIVE \
    CTL_CODE( \
        FILE_DEVICE_COMOTE_VIRTUAL_HID, \
        0x804U, \
        METHOD_BUFFERED, \
        FILE_WRITE_DATA)

#define IOCTL_COMOTE_MOUSE_ABSOLUTE \
    CTL_CODE( \
        FILE_DEVICE_COMOTE_VIRTUAL_HID, \
        0x805U, \
        METHOD_BUFFERED, \
        FILE_WRITE_DATA)

static const GUID GUID_DEVINTERFACE_COMOTE_VIRTUAL_HID_PHASE2 =
{
    0xba2bc8d8,
    0x8d1b,
    0x48e4,
    { 0x8e, 0xa7, 0x79, 0x13, 0x9b, 0x13, 0x07, 0xa8 }
};

#pragma pack(push, 1)

typedef struct _COMOTE_COMMAND_HEADER
{
    ULONG Size;
    ULONG Magic;
    ULONG ProtocolVersion;
    ULONG Sequence;
} COMOTE_COMMAND_HEADER, *PCOMOTE_COMMAND_HEADER;

typedef struct _COMOTE_VERSION_RESPONSE
{
    ULONG Size;
    ULONG ProtocolVersion;
    ULONG DriverVersionMajor;
    ULONG DriverVersionMinor;
    ULONG DriverVersionPatch;
    ULONG DriverVersionBuild;
} COMOTE_VERSION_RESPONSE, *PCOMOTE_VERSION_RESPONSE;

typedef struct _COMOTE_CAPABILITIES_RESPONSE
{
    ULONG Size;
    ULONG ProtocolVersion;
    ULONG Capabilities;
    ULONG MaximumKeyboardKeys;
    ULONG MaximumMouseButtons;
    LONG MaximumMouseDelta;
    LONG MaximumWheelDelta;
    ULONG MaximumAbsoluteCoordinate;
} COMOTE_CAPABILITIES_RESPONSE, *PCOMOTE_CAPABILITIES_RESPONSE;

typedef struct _COMOTE_RELEASE_ALL_REQUEST
{
    COMOTE_COMMAND_HEADER Header;
} COMOTE_RELEASE_ALL_REQUEST, *PCOMOTE_RELEASE_ALL_REQUEST;

typedef struct _COMOTE_KEYBOARD_STATE_REQUEST
{
    COMOTE_COMMAND_HEADER Header;
    UCHAR Modifiers;
    UCHAR Reserved;
    UCHAR Keys[COMOTE_KEYBOARD_MAX_KEYS];
} COMOTE_KEYBOARD_STATE_REQUEST, *PCOMOTE_KEYBOARD_STATE_REQUEST;

typedef struct _COMOTE_MOUSE_RELATIVE_REQUEST
{
    COMOTE_COMMAND_HEADER Header;
    UCHAR Buttons;
    UCHAR Reserved;
    SHORT DeltaX;
    SHORT DeltaY;
    CHAR VerticalWheel;
    CHAR HorizontalWheel;
} COMOTE_MOUSE_RELATIVE_REQUEST, *PCOMOTE_MOUSE_RELATIVE_REQUEST;

typedef struct _COMOTE_MOUSE_ABSOLUTE_REQUEST
{
    COMOTE_COMMAND_HEADER Header;
    UCHAR Buttons;
    UCHAR Reserved;
    USHORT X;
    USHORT Y;
    CHAR VerticalWheel;
    CHAR HorizontalWheel;
} COMOTE_MOUSE_ABSOLUTE_REQUEST, *PCOMOTE_MOUSE_ABSOLUTE_REQUEST;

#pragma pack(pop)

C_ASSERT(sizeof(COMOTE_COMMAND_HEADER) == 16);
C_ASSERT(sizeof(COMOTE_VERSION_RESPONSE) == 24);
C_ASSERT(sizeof(COMOTE_CAPABILITIES_RESPONSE) == 32);
C_ASSERT(sizeof(COMOTE_RELEASE_ALL_REQUEST) == 16);
C_ASSERT(sizeof(COMOTE_KEYBOARD_STATE_REQUEST) == 24);
C_ASSERT(sizeof(COMOTE_MOUSE_RELATIVE_REQUEST) == 24);
C_ASSERT(sizeof(COMOTE_MOUSE_ABSOLUTE_REQUEST) == 24);
