#Requires -Version 5.1
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$sourcePath = Join-Path $PSScriptRoot "ComoteVirtualHidPhase2.c"
$headerPath = Join-Path $PSScriptRoot "ComoteVirtualHidPhase2.h"
$protocolPath = Join-Path $PSScriptRoot "ComoteVirtualHidProtocol.h"
$projectPath = Join-Path $PSScriptRoot "ComoteVirtualHidPhase2.vcxproj"
$infPath = Join-Path $PSScriptRoot "ComoteVirtualHidPhase2.inf"
$probePath = Join-Path `
    $PSScriptRoot `
    "Probe\ComoteVirtualHidProbe.c"
$probeProjectPath = Join-Path `
    $PSScriptRoot `
    "Probe\ComoteVirtualHidProbe.vcxproj"
$buildPath = Join-Path $PSScriptRoot "Build-Phase2.ps1"
$vmBuildPath = Join-Path $PSScriptRoot "Invoke-Phase2VmBuild.ps1"

foreach ($path in @(
    $sourcePath,
    $headerPath,
    $protocolPath,
    $projectPath,
    $infPath,
    $probePath,
    $probeProjectPath,
    $buildPath,
    $vmBuildPath
)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required Phase 2 source file is missing: $path"
    }
}

$phase1Root = Join-Path `
    (Split-Path -Parent $PSScriptRoot) `
    "ComoteVirtualHid"
$phase1Baseline = [ordered]@{
    "ComoteVirtualHid.c" =
        "F36B34CD1654FBEA505FCB5F88CBE69DC2C14F57929CD89DA80423BE345CE6B3"
    "ComoteVirtualHid.h" =
        "BA066870F397B2E51D872E94057EF31A877B6838D22D81E93B3669AB05376967"
    "ComoteVirtualHid.inf" =
        "5E54C1DDAC7BB039ABA94F7C4714706ADEC371284BD36388CE92EB48C4F1261B"
    "ComoteVirtualHid.vcxproj" =
        "A4FA2554572AA8083A2D84AD97E140BE72D5597309EB29ACA5B6BB998FBDC523"
}
foreach ($entry in $phase1Baseline.GetEnumerator()) {
    $phase1Path = Join-Path $phase1Root $entry.Key
    if (-not (Test-Path -LiteralPath $phase1Path -PathType Leaf)) {
        throw "The proven Phase 1 baseline file is missing: $phase1Path"
    }
    $actualHash = (
        Get-FileHash `
            -Algorithm SHA256 `
            -LiteralPath $phase1Path
    ).Hash
    if ($actualHash -ne $entry.Value) {
        throw "The proven Phase 1 baseline changed: $phase1Path"
    }
}

$source = Get-Content -LiteralPath $sourcePath -Raw
$header = Get-Content -LiteralPath $headerPath -Raw
$protocol = Get-Content -LiteralPath $protocolPath -Raw
$combinedDriver = @(
    $source,
    $header,
    $protocol
) -join "`n"

foreach ($requiredText in @(
    "VHF_CONFIG_INIT",
    "VhfCreate",
    "VhfStart",
    "VhfReadReportSubmit",
    "VhfDelete",
    "WdfDeviceCreateDeviceInterface",
    "GUID_DEVINTERFACE_COMOTE_VIRTUAL_HID_PHASE2",
    "FILE_AUTOGENERATED_DEVICE_NAME",
    "WdfDeviceInitAssignSDDLString",
    "SDDL_DEVOBJ_SYS_ALL",
    "securityDescriptor = SDDL_DEVOBJ_SYS_ALL",
    "WdfDeviceInitSetExclusive",
    "WdfSynchronizationScopeDevice",
    "WdfIoQueueDispatchSequential",
    "ComoteEvtDeviceFileCreate",
    "ComoteEvtFileCleanup",
    "ComoteEvtDeviceD0Entry",
    "ComoteEvtDeviceD0Exit",
    "ComoteEvtDeviceCleanup",
    "ComoteReleaseAll",
    "ComoteSubmitAbsoluteMouseReport",
    "ReleasePending",
    "AbsoluteMouseInitialized",
    "RelativeMouseButtons",
    "AbsoluteMouseButtons",
    "COMOTE_ABSOLUTE_MOUSE_REPORT_ID",
    "COMOTE_ABSOLUTE_MOUSE_REPORT, *PCOMOTE_ABSOLUTE_MOUSE_REPORT",
    "C_ASSERT(sizeof(COMOTE_ABSOLUTE_MOUSE_REPORT) == 8)",
    "EVT_WDF_DEVICE_CONTEXT_CLEANUP",
    "InputBufferLength != sizeof",
    "InputBufferLength != 0",
    "Header->Sequence != DeviceContext->LastSequence + 1",
    "mouseRequest->DeltaX <",
    "mouseRequest->DeltaY <",
    "-COMOTE_MOUSE_MAX_DELTA",
    "mouseRequest->VerticalWheel <",
    "mouseRequest->HorizontalWheel <",
    "-COMOTE_MOUSE_MAX_WHEEL_DELTA",
    "mouseRequest->X >",
    "mouseRequest->Y >",
    "COMOTE_MOUSE_MAX_ABSOLUTE_COORDINATE",
    "COMOTE_MOUSE_BUTTON_MASK",
    "COMOTE_KEYBOARD_MAX_KEYS",
    "STATUS_INVALID_BUFFER_SIZE",
    "STATUS_INVALID_PARAMETER"
)) {
    if ($combinedDriver.IndexOf(
            $requiredText,
            [StringComparison]::Ordinal) -lt 0) {
        throw "Required Phase 2 driver boundary is missing: $requiredText"
    }
}

foreach ($forbiddenText in @(
    "FILE_ANY_ACCESS",
    "METHOD_NEITHER",
    "SDDL_DEVOBJ_SYS_ALL_ADM_ALL",
    ";;;BA",
    ";;;WD",
    "IoCreateSymbolicLink",
    "MmMapIoSpace",
    "MmMapLockedPages",
    "ZwCreateFile",
    "PsCreateSystemThread",
    "WdfTimerCreate",
    "WdfWorkItemCreate",
    "MINSHORT",
    "MINCHAR"
)) {
    if ($combinedDriver.IndexOf(
            $forbiddenText,
            [StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "Phase 2 driver crossed its safety boundary: $forbiddenText"
    }
}

foreach ($requiredSourceText in @(
    "0x85, COMOTE_ABSOLUTE_MOUSE_REPORT_ID",
    "case IOCTL_COMOTE_MOUSE_ABSOLUTE:",
    "COMOTE_CAPABILITY_MOUSE_ABSOLUTE |",
    "response->MaximumAbsoluteCoordinate =",
    "absoluteMouseReport.X = DeviceContext->AbsoluteMouseX;",
    "absoluteMouseReport.Y = DeviceContext->AbsoluteMouseY;",
    "DeviceContext->AbsoluteMouseButtons = 0;",
    "deviceContext->AbsoluteMouseInitialized = TRUE;"
)) {
    if ($source.IndexOf(
            $requiredSourceText,
            [StringComparison]::Ordinal) -lt 0) {
        throw "Required Phase 2 source implementation is missing: $requiredSourceText"
    }
}

$descriptorMatch = [regex]::Match(
    $source,
    "static\s+UCHAR\s+ComoteReportDescriptor\[\]\s*=\s*\{(?<body>.*?)\};",
    [Text.RegularExpressions.RegexOptions]::Singleline)
if (-not $descriptorMatch.Success) {
    throw "The Phase 2 HID report descriptor was not found."
}
$descriptorTokens = New-Object "System.Collections.Generic.List[int]"
foreach ($tokenMatch in [regex]::Matches(
    $descriptorMatch.Groups["body"].Value,
    "0x[0-9A-Fa-f]+|COMOTE_(?:KEYBOARD|MOUSE|ABSOLUTE_MOUSE)_REPORT_ID"
)) {
    switch ($tokenMatch.Value) {
        "COMOTE_KEYBOARD_REPORT_ID" {
            $descriptorTokens.Add(1)
        }
        "COMOTE_MOUSE_REPORT_ID" {
            $descriptorTokens.Add(2)
        }
        "COMOTE_ABSOLUTE_MOUSE_REPORT_ID" {
            $descriptorTokens.Add(3)
        }
        default {
            $descriptorTokens.Add(
                [Convert]::ToInt32(
                    $tokenMatch.Value.Substring(2),
                    16))
        }
    }
}
$reportSize = 0
$reportCount = 0
$reportId = 0
$reportBits = @{}
$reportInputFlags = @{}
$collectionDepth = 0
for ($index = 0; $index -lt $descriptorTokens.Count;) {
    $prefix = $descriptorTokens[$index]
    $index++
    if ($prefix -eq 0xFE) {
        throw "Long HID items are not allowed in the Phase 2 descriptor."
    }
    $dataSize = $prefix -band 3
    if ($dataSize -eq 3) {
        $dataSize = 4
    }
    if ($index + $dataSize -gt $descriptorTokens.Count) {
        throw "The Phase 2 HID report descriptor is truncated."
    }
    $value = 0
    for ($byteIndex = 0; $byteIndex -lt $dataSize; $byteIndex++) {
        $value = $value -bor (
            $descriptorTokens[$index] -shl (8 * $byteIndex))
        $index++
    }
    $itemType = ($prefix -shr 2) -band 3
    $itemTag = ($prefix -shr 4) -band 15
    if ($itemType -eq 1 -and $itemTag -eq 7) {
        $reportSize = $value
    }
    elseif ($itemType -eq 1 -and $itemTag -eq 8) {
        $reportId = $value
    }
    elseif ($itemType -eq 1 -and $itemTag -eq 9) {
        $reportCount = $value
    }
    elseif ($itemType -eq 0 -and $itemTag -eq 8) {
        if ($reportId -eq 0) {
            throw "A Phase 2 input item has no report ID."
        }
        if (-not $reportBits.ContainsKey($reportId)) {
            $reportBits[$reportId] = 0
            $reportInputFlags[$reportId] = @()
        }
        $reportBits[$reportId] += $reportSize * $reportCount
        $reportInputFlags[$reportId] += $value
    }
    elseif ($itemType -eq 0 -and $itemTag -eq 10) {
        $collectionDepth++
    }
    elseif ($itemType -eq 0 -and $itemTag -eq 12) {
        $collectionDepth--
        if ($collectionDepth -lt 0) {
            throw "The Phase 2 HID collection stack underflowed."
        }
    }
}
if ($collectionDepth -ne 0) {
    throw "The Phase 2 HID collections are unbalanced."
}
$expectedReportBytes = @{
    1 = 9
    2 = 8
    3 = 8
}
$expectedInputFlags = @{
    1 = "2,3,0"
    2 = "2,3,6,6,6"
    3 = "2,3,2,6,6"
}
foreach ($expectedReportId in @(1, 2, 3)) {
    if (-not $reportBits.ContainsKey($expectedReportId)) {
        throw "The Phase 2 HID report ID is missing: $expectedReportId"
    }
    $actualReportBytes = 1 + [int][Math]::Ceiling(
        $reportBits[$expectedReportId] / 8)
    if ($actualReportBytes -ne $expectedReportBytes[$expectedReportId]) {
        throw (
            "The Phase 2 HID report size is invalid for report ID {0}: {1}" -f
            $expectedReportId,
            $actualReportBytes)
    }
    $actualInputFlags = $reportInputFlags[$expectedReportId] -join ","
    if ($actualInputFlags -ne $expectedInputFlags[$expectedReportId]) {
        throw (
            "The Phase 2 HID input flags are invalid for report ID {0}: {1}" -f
            $expectedReportId,
            $actualInputFlags)
    }
}

foreach ($requiredProtocolText in @(
    "METHOD_BUFFERED",
    "FILE_READ_DATA",
    "FILE_WRITE_DATA",
    "IOCTL_COMOTE_GET_VERSION",
    "IOCTL_COMOTE_GET_CAPABILITIES",
    "IOCTL_COMOTE_RELEASE_ALL",
    "IOCTL_COMOTE_SET_KEYBOARD_STATE",
    "IOCTL_COMOTE_MOUSE_RELATIVE",
    "IOCTL_COMOTE_MOUSE_ABSOLUTE",
    "COMOTE_PROTOCOL_MAGIC",
    "#define COMOTE_PROTOCOL_VERSION 2UL",
    "COMOTE_CAPABILITY_SYSTEM_ONLY",
    "COMOTE_CAPABILITY_RELEASE_ON_CLOSE",
    "COMOTE_CAPABILITY_RELEASE_ON_POWER_DOWN",
    "COMOTE_CAPABILITY_MOUSE_ABSOLUTE",
    "#define COMOTE_MOUSE_MAX_ABSOLUTE_COORDINATE 32767L",
    "C_ASSERT(sizeof(COMOTE_CAPABILITIES_RESPONSE) == 32)",
    "C_ASSERT(sizeof(COMOTE_KEYBOARD_STATE_REQUEST) == 24)",
    "C_ASSERT(sizeof(COMOTE_MOUSE_RELATIVE_REQUEST) == 24)",
    "C_ASSERT(sizeof(COMOTE_MOUSE_ABSOLUTE_REQUEST) == 24)"
)) {
    if ($protocol.IndexOf(
            $requiredProtocolText,
            [StringComparison]::Ordinal) -lt 0) {
        throw "Required Phase 2 protocol boundary is missing: $requiredProtocolText"
    }
}

$fileCleanupIndex = $source.IndexOf(
    "ComoteEvtFileCleanup(",
    [StringComparison]::Ordinal)
$fileCleanupReleaseIndex = $source.IndexOf(
    "(VOID)ComoteReleaseAll(deviceContext);",
    $fileCleanupIndex,
    [StringComparison]::Ordinal)
$powerExitIndex = $source.IndexOf(
    "ComoteEvtDeviceD0Exit(",
    [StringComparison]::Ordinal)
$powerReleaseIndex = $source.IndexOf(
    "(VOID)ComoteReleaseAll(deviceContext);",
    $powerExitIndex,
    [StringComparison]::Ordinal)
$deviceCleanupIndex = $source.IndexOf(
    "ComoteEvtDeviceCleanup(",
    [StringComparison]::Ordinal)
$deviceCleanupReleaseIndex = $source.IndexOf(
    "(VOID)ComoteReleaseAll(deviceContext);",
    $deviceCleanupIndex,
    [StringComparison]::Ordinal)
$deviceCleanupDeleteIndex = $source.IndexOf(
    "VhfDelete(",
    $deviceCleanupReleaseIndex,
    [StringComparison]::Ordinal)
$powerEntryIndex = $source.IndexOf(
    "ComoteEvtDeviceD0Entry(",
    [StringComparison]::Ordinal)
$powerEntryPendingIndex = $source.IndexOf(
    "if (!deviceContext->ReleasePending)",
    $powerEntryIndex,
    [StringComparison]::Ordinal)
$powerEntryReleaseIndex = $source.IndexOf(
    "return ComoteReleaseAll(deviceContext);",
    $powerEntryPendingIndex,
    [StringComparison]::Ordinal)
$releaseAllIndex = $source.IndexOf(
    "ComoteReleaseAll(",
    [StringComparison]::Ordinal)
$releasePendingSetIndex = $source.IndexOf(
    "DeviceContext->ReleasePending = TRUE;",
    $releaseAllIndex,
    [StringComparison]::Ordinal)
$keyboardNeutralSubmitIndex = $source.IndexOf(
    "keyboardStatus = ComoteSubmitKeyboardReport(",
    $releasePendingSetIndex,
    [StringComparison]::Ordinal)
$relativeNeutralSubmitIndex = $source.IndexOf(
    "mouseStatus = ComoteSubmitMouseReport(",
    $keyboardNeutralSubmitIndex,
    [StringComparison]::Ordinal)
$absoluteInitializedGuardIndex = $source.IndexOf(
    "if (DeviceContext->AbsoluteMouseInitialized)",
    $relativeNeutralSubmitIndex,
    [StringComparison]::Ordinal)
$absoluteNeutralSubmitIndex = $source.IndexOf(
    "absoluteMouseStatus = ComoteSubmitAbsoluteMouseReport(",
    $absoluteInitializedGuardIndex,
    [StringComparison]::Ordinal)
$releasePendingClearIndex = $source.IndexOf(
    "DeviceContext->ReleasePending = FALSE;",
    $absoluteNeutralSubmitIndex,
    [StringComparison]::Ordinal)
$fileCreateIndex = $source.IndexOf(
    "ComoteEvtDeviceFileCreate(",
    [StringComparison]::Ordinal)
$fileCreateReleaseIndex = $source.IndexOf(
    "status = ComoteReleaseAll(deviceContext);",
    $fileCreateIndex,
    [StringComparison]::Ordinal)
$fileCreateSequenceResetIndex = $source.IndexOf(
    "deviceContext->LastSequence = 0;",
    $fileCreateReleaseIndex,
    [StringComparison]::Ordinal)
$absoluteIoctlIndex = $source.IndexOf(
    "case IOCTL_COMOTE_MOUSE_ABSOLUTE:",
    [StringComparison]::Ordinal)
$absoluteSubmitIndex = $source.IndexOf(
    "status = ComoteSubmitAbsoluteMouseReport(",
    $absoluteIoctlIndex,
    [StringComparison]::Ordinal)
$absoluteSubmitSuccessIndex = $source.IndexOf(
    "if (NT_SUCCESS(status))",
    $absoluteSubmitIndex,
    [StringComparison]::Ordinal)
$absoluteInitializeIndex = $source.IndexOf(
    "deviceContext->AbsoluteMouseInitialized = TRUE;",
    $absoluteSubmitSuccessIndex,
    [StringComparison]::Ordinal)
$absoluteSequenceIndex = $source.IndexOf(
    "deviceContext->LastSequence =",
    $absoluteInitializeIndex,
    [StringComparison]::Ordinal)
if ($fileCleanupIndex -lt 0 -or
    $fileCleanupReleaseIndex -lt $fileCleanupIndex -or
    $powerEntryIndex -lt 0 -or
    $powerEntryPendingIndex -lt $powerEntryIndex -or
    $powerEntryReleaseIndex -lt $powerEntryPendingIndex -or
    $releaseAllIndex -lt 0 -or
    $releasePendingSetIndex -lt $releaseAllIndex -or
    $keyboardNeutralSubmitIndex -lt $releasePendingSetIndex -or
    $relativeNeutralSubmitIndex -lt $keyboardNeutralSubmitIndex -or
    $absoluteInitializedGuardIndex -lt $relativeNeutralSubmitIndex -or
    $absoluteNeutralSubmitIndex -lt $absoluteInitializedGuardIndex -or
    $releasePendingClearIndex -lt $absoluteNeutralSubmitIndex -or
    $fileCreateIndex -lt 0 -or
    $fileCreateReleaseIndex -lt $fileCreateIndex -or
    $fileCreateSequenceResetIndex -lt $fileCreateReleaseIndex -or
    $absoluteIoctlIndex -lt 0 -or
    $absoluteSubmitIndex -lt $absoluteIoctlIndex -or
    $absoluteSubmitSuccessIndex -lt $absoluteSubmitIndex -or
    $absoluteInitializeIndex -lt $absoluteSubmitSuccessIndex -or
    $absoluteSequenceIndex -lt $absoluteInitializeIndex -or
    $powerExitIndex -lt 0 -or
    $powerReleaseIndex -lt $powerExitIndex -or
    $deviceCleanupIndex -lt 0 -or
    $deviceCleanupReleaseIndex -lt $deviceCleanupIndex -or
    $deviceCleanupDeleteIndex -lt $deviceCleanupReleaseIndex) {
    throw "Release-all cleanup ordering is invalid."
}

$project = Get-Content -LiteralPath $projectPath -Raw
foreach ($requiredProjectText in @(
    "<SignMode>Off</SignMode>",
    "<Inf2CatUseLocalTime>true</Inf2CatUseLocalTime>",
    "WindowsKernelModeDriver10.0",
    "VhfKm.lib",
    "Wdmsec.lib",
    "ControlFlowGuard",
    "SpectreMitigation",
    "TreatWarningAsError"
)) {
    if ($project.IndexOf(
            $requiredProjectText,
            [StringComparison]::OrdinalIgnoreCase) -lt 0) {
        throw "Required Phase 2 project boundary is missing: $requiredProjectText"
    }
}

$probe = Get-Content -LiteralPath $probePath -Raw
foreach ($requiredProbeText in @(
    "SetupDiGetClassDevsW",
    "SetupDiEnumDeviceInterfaces",
    "CreateFileW",
    "GENERIC_READ | GENERIC_WRITE",
    "DeviceIoControl",
    "RunInfo",
    "RunRelease",
    "RunTap",
    "RunMouse",
    "RunAbsoluteMouse",
    "RunParserSelfTest",
    "_Success_(return != FALSE)",
    'L"parser-selftest"',
    'L"-32768"',
    'L"-128"',
    'L"-1"',
    'L"info"',
    'L"release"',
    'L"tap"',
    'L"move"',
    'L"click"',
    'L"wheel"',
    'L"absolute"',
    'L"absolute-click"',
    'L"absolute-wheel"',
    "COMOTE_MOUSE_MAX_ABSOLUTE_COORDINATE",
    "CloseHandle"
)) {
    if ($probe.IndexOf(
            $requiredProbeText,
            [StringComparison]::Ordinal) -lt 0) {
        throw "Required Phase 2 probe boundary is missing: $requiredProbeText"
    }
}
foreach ($forbiddenProbeText in @(
    "WinHttp",
    "WinInet",
    "WSAStartup",
    "CreateService",
    "OpenSCManager",
    "ShellExecute",
    "CreateProcess",
    "SendInput",
    "keybd_event",
    "mouse_event"
)) {
    if ($probe.IndexOf(
            $forbiddenProbeText,
            [StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "Phase 2 probe crossed its safety boundary: $forbiddenProbeText"
    }
}

$probeProject = Get-Content -LiteralPath $probeProjectPath -Raw
foreach ($requiredProbeProjectText in @(
    "Setupapi.lib",
    "CompileAsC",
    "ControlFlowGuard",
    "SpectreMitigation",
    "TreatWarningAsError"
)) {
    if ($probeProject.IndexOf(
            $requiredProbeProjectText,
            [StringComparison]::OrdinalIgnoreCase) -lt 0) {
        throw "Required probe project boundary is missing: $requiredProbeProjectText"
    }
}

$inf = Get-Content -LiteralPath $infPath -Raw
foreach ($requiredInfText in @(
    'ROOT\COMOTEVIRTUALHID_PHASE2',
    '"LowerFilters",0x00010000,"vhf"',
    "DefaultDestDir=13",
    "ComoteDriverCopy=13",
    "ServiceBinary=%13%\ComoteVirtualHidPhase2.sys",
    "NTamd64.10.0...19045",
    "StartType=3",
    "PnpLockdown=1"
)) {
    if ($inf.IndexOf(
            $requiredInfText,
            [StringComparison]::OrdinalIgnoreCase) -lt 0) {
        throw "Required Phase 2 INF boundary is missing: $requiredInfText"
    }
}

$buildScripts = @(
    (Get-Content -LiteralPath $buildPath -Raw),
    (Get-Content -LiteralPath $vmBuildPath -Raw)
) -join "`n"
foreach ($requiredBuildText in @(
    "Test-Phase2Boundary.ps1",
    "ComoteVirtualHidPhase2.vcxproj",
    "ComoteVirtualHidProbe.vcxproj",
    "/p:SignMode=Off",
    "/p:RunCodeAnalysis=true",
    "InfVerif.exe",
    "Inf2Cat.exe",
    "Get-AuthenticodeSignature",
    "phase2-unsigned",
    "ComoteVirtualHidPhase2.cat",
    "unsigned CAT",
    "No certificate was created",
    "no driver was installed"
)) {
    if ($buildScripts.IndexOf(
            $requiredBuildText,
            [StringComparison]::OrdinalIgnoreCase) -lt 0) {
        throw "Required Phase 2 build boundary is missing: $requiredBuildText"
    }
}
foreach ($forbiddenBuildText in @(
    "pnputil",
    "devgen",
    "devcon",
    "bcdedit",
    "New-SelfSignedCertificate",
    "certutil",
    "signtool",
    "verifier.exe",
    "sc.exe",
    "dism.exe",
    "Add-WindowsDriver",
    "New-Service",
    "Start-Service",
    "Restart-Computer",
    "Stop-Computer"
)) {
    if ($buildScripts.IndexOf(
            $forbiddenBuildText,
            [StringComparison]::OrdinalIgnoreCase) -ge 0) {
        throw "Phase 2 build crossed its safety boundary: $forbiddenBuildText"
    }
}

Write-Host "Phase 2 source and build boundaries verified." -ForegroundColor Green
